/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-XML-Minify.h
 #	source generated by 4D Plugin Wizard
 #	Project : XML Minify
 #	author : miyako
 #	2020/01/08
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_XML_MINIFY_H
#define PLUGIN_XML_MINIFY_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"

#include <libxml/xmlmemory.h>
#include <libxml/debugXML.h>
#include <libxml/HTMLtree.h>
#include <libxml/xmlIO.h>
#include <libxml/parser.h>
#include <libxml/xinclude.h>
#include <libxml/catalog.h>

#pragma mark -

void XML_Minify(PA_PluginParameters params);

#endif /* PLUGIN_XML_MINIFY_H */
